title: Abhishek Jha
url: "https://abskjha.github.io"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/abskjha"
footer_text: "Abhishek Jha (c) 2018"

sass:
    style: compressed
    sass_dir: _sass

include: ["_includes"]